---
title: "SPS-DATA607-WEEK10"
author: "Tage N Singh"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```yaml
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
```

##Setup 

```{r setup}
knitr::opts_chunk$set(include = FALSE)
library(tidytext)
library(janeaustenr)
library(dplyr)
library(stringr)
library(rvest)
library(ggmap)
library(leaflet)
library(RColorBrewer)
library(scrapeR)
library(gutenbergr)


```

```{r afinn, echo=FALSE}
get_sentiments("afinn")


```

```{r bing, echo=FALSE}

get_sentiments("bing")


```

```{r nrc, echo=FALSE}

get_sentiments("nrc")


```

```{r search-cran}


```

```{r emily braunte}

text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")

library(dplyr)

text_df <- tibble(line = 1:4, text = text)


text_df %>%
  unnest_tokens(word, text)


```

```{r}

original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, 
                                     regex("^chapter [\\divxlc]",
                                           ignore_case = TRUE)))) %>%
  ungroup()

original_books



tidy_books <- original_books %>%
  unnest_tokens(word, text)



tidy_books


data(stop_words)

tidy_books <- tidy_books %>%
  anti_join(stop_words)


tidy_books %>%
  count(word, sort = TRUE) 

```
```{r ch1-gutenberg}




longfellow <- gutenberg_download(c(5436, 23332, 25153))


tidy_longfellow <- longfellow %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)


tidy_longfellow %>%
  count(word, sort = TRUE)

```

